mapping = {
	California:'US-CA',
	Texas:'US-TX',
	Florida:'US-FL',
	'New York':'US-NY',
	Pennsylvania:'US-PA',
	Illinois:'US-IL',
	Ohio:'US-OH',
	Georgia:'US-GA',
	'North Carolina':'US-NC',
	Michigan:'US-MI',
	'New Jersey':'US-NJ',
	Virginia:'US-VA',
	Washington:'US-WA',
	Arizona:'US-AZ',
	Massachusetts:'US-MA',
	Tennessee:'US-TN',
	Indiana:'US-IN',
	Missouri:'US-MO',
	Maryland:'US-MD',
	Wisconsin:'US-WI',
	Colorado:'US-CO',
	Minnesota:'US-MN',
	'South Carolina':'US-SC',
	Alabama:'US-AL',
	Louisiana:'US-LA',
	Kentucky:'US-KY',
	Oregon:'US-OR',
	Oklahoma:'US-OK',
	Connecticut:'US-CT',
	Utah:'US-UT',
	// 'Puerto Rico':'US-IA',
	Iowa:'US-IA',
	Nevada:'US-NV',
	Arkansas:'US-AR',
	Mississippi:'US-MS',
	Kansas:'US-KS',
	'New Mexico':'US-NM',
	Nebraska:'US-NE',
	'West Virginia':'US-WV',
	Idaho:'US-ID',
	Hawaii:'US-HI',
	'New Hampshire':'US-NH',
	Maine:'US-ME',
	Montana:'US-MT',
	'Rhode Island':'US-RI',
	Delaware:'US-DE',
	'South Dakota':'US-SD',
	'North Dakota':'US-ND',
	Alaska:'US-AK',
	'District of Columbia':'US-DC',
	Vermont:'US-VT',
	Wyoming:'US-WY'
}

module.exports = mapping
